adding zabbixServer.DB_SERVER_PORT
cetic/helm-zabbix pull request #21
Opened 2021-02-12 03:00 UTC by dnplkndll

#### What this PR does / why we need it:

adds the postgresql port option to use a db service, like digital ocean.  

#### Special notes for your reviewer:
tested and works, wonder if there is a reason for the 2 sets of db credentials if they need to be the same?

#### Checklist
- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2021-02-12 03:04 UTC, dnplkndll commented
@AyadiAmen 
@alexnuttinck
@aeciopires

2021-02-19 08:15 UTC, alexnuttinck requested changes
Thanks for your PR, Could you take into account my two comments before merging?

2021-02-19 08:15 UTC, alexnuttinck commented on Chart.yaml
> +version: 0.2.2
Could you bump the Chart to v0.3.2?

2021-02-19 08:15 UTC, alexnuttinck commented on README.md
> +| zabbixServer.DB_SERVER_PORT | string | `5432` | Address of database host |
host -> port

2021-02-19 12:01 UTC, aeciopires commented
Hi @dnplkndll!

Thank you very much for your collaboration. I made some comments that need to be adjusted in your Pull Request.

In CONTRIBUTING.md file has instructions for install helm-docs command to update documentation and update table with new values.

... Install the follow packages: git, kubectl, helm, helm-docs. See this tutorial...

and

...Run command helm-docs to update content of README.md file using the README.md.gotmpl template...
Can you execute these instructions?

2021-09-14 14:06 UTC, scoopex commented on Chart.yaml
> +version: 0.2.2
0.3.3

2021-09-30 17:57 UTC, aeciopires commented
Hi @dnplkndll!

Thank you very much for your contribution.

As your Pull Request has been open for a long time, I took the initiative to include the solution in this other Pull Request. https://github.com/cetic/helm-zabbix/pull/35

2021-09-30 17:57 UTC, closed without merging