Honor nodeSelector, tolerations, and affinity values from values.yaml
cetic/helm-zabbix pull request #41
Opened 2022-01-29 22:06 UTC by adamcharnock

#### What this PR does / why we need it:

The `nodeSelector`, `tolerations`, and `affinity` values in the `values.yaml` file were not being implemented in the templates. This PR resolves this.

#### Special notes for your reviewer:

#### Checklist

- [x] [DCO](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#sign-your-work) signed
- [x] Chart Version bumped
- [x] Variables are documented in the README.md

2022-01-30 04:54 UTC, aeciopires requested changes
Hello @adamcharnock!

Thanks for your contribution!

I suggest the change for new lines because are more flexible. Do you agree?

2022-01-30 04:54 UTC, aeciopires commented on templates/StatefulSet-zabbix-proxy.yaml
> +
```suggestion
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

2022-01-30 04:54 UTC, aeciopires commented on templates/StatefulSet-zabbix-server.yaml
> +
```suggestion
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

2022-01-30 04:54 UTC, aeciopires commented on templates/Web-deployment.yaml
> +
```suggestion
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

2022-01-30 04:54 UTC, aeciopires commented on templates/StatefulSet-zabbix-proxy.yaml
> +
Hello @adamcharnock!

Thanks for your contribution!

I suggest the change for new lines because are more flexible. Do you agree?

2022-01-30 04:54 UTC, aeciopires commented on templates/StatefulSet-zabbix-server.yaml
> +
Hello @adamcharnock!

Thanks for your contribution!

I suggest the change for new lines because are more flexible. Do you agree?

2022-01-30 04:54 UTC, aeciopires commented on templates/Web-deployment.yaml
> +
Hello @adamcharnock!

Thanks for your contribution!

I suggest the change for new lines because are more flexible. Do you agree?

2022-01-30 13:34 UTC, adamcharnock commented on templates/StatefulSet-zabbix-proxy.yaml
> +
Committing suggestion by @aeciopires

2022-01-30 13:35 UTC, adamcharnock commented
Fine by me!

2022-01-30 23:17 UTC, aeciopires requested changes
Hi @adamcharnock! 

I made some comments. Could you adjust?

2022-01-30 23:17 UTC, aeciopires commented on templates/StatefulSet-zabbix-proxy.yaml
> +      nodeSelector:
Hi @adamcharnock!

Could you remove the lines 28 to 33?
The goal is to leave only the lines 34 to 45 that will be filled in only when someone sets the custom values for these properties.

2022-01-30 23:17 UTC, aeciopires commented on templates/StatefulSet-zabbix-server.yaml
> +      nodeSelector:
Hi @adamcharnock!

Could you remove the lines 27 to 32?
The goal is to leave only the lines 33 to 44 that will be filled in only when someone sets the custom values for these properties.

2022-01-30 23:17 UTC, aeciopires commented on templates/Web-deployment.yaml
> +      nodeSelector:
Hi @adamcharnock!

Could you remove the lines 26 to 31?
The goal is to leave only the lines 32 to 43 that will be filled in only when someone sets the custom values for these properties.

2022-01-30 23:51 UTC, adamcharnock commented
Apologies @aeciopires, should be resolved now. The GitHub web UI didn't quite do what I expected.

2022-01-31 00:28 UTC, aeciopires approved these changes
Thanks @adamcharnock!

 Yes I understand! I also thought he swapped the lines but it just does the append

2022-01-31 00:28 UTC, merged